CREATE TABLE `proxy_ip` (
`id` INT(11) unsigned NOT NULL AUTO_INCREMENT,
`ip` VARCHAR(20) DEFAULT NULL COMMENT 'IP',
`port` INT(11) DEFAULT 0 COMMENT '端口',
`speed` INT(11) DEFAULT 0 COMMENT '速度',
`proxy_type` VARCHAR(20) DEFAULT 'HTTP' COMMENT '代理类型',
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;